# title: "Shourov Joader"
# header_pages:
#   - index.md
#   - cv.md
#   - research.md
# description: "Undergraduate Student at BUET"
# baseurl: "" # leave empty for GitHub Pages
# url: "https://jdickamazz.github.io"
# remote_theme: pages-themes/minimal@v0.2.0
# plugins:
# - jekyll-remote-theme # add this line to the plugins list if you already have one

title: "Shourov Joarder's Portfolio"
theme: jekyll-theme-minimal
description: "A personal website for Shourov Joarder"
